spring:
  h2:
    console:
      path: /h2
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties.hibernate.format_sql: true

fingate.tasks.fees.schedule: 0 0 9 ? * MON-FRI
