spring:
  h2:
    console:
      path: /h2
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties.hibernate.format_sql: true

fingate:
  free_account_number_threshold: 2
  tasks:
    fees.schedule: 0 0 9 ? * MON-FRI
    gifts.birthday.schedule: 0 0 9 ? * MON-FRI
  jwt:
    secret: testFinGateEliseev
    expiration_millis: 86400000
